name: AziPluginMessaging
main: net.azisaba.azipluginmessaging.spigot.SpigotPlugin
version: 2.3.0-SNAPSHOT
depend:
  - LuckPerms
commands:
  azipluginmessaging:
    permission: azipluginmessaging.use_command
