name: AziPluginMessaging
main: net.azisaba.azipluginmessaging.spigot.SpigotPlugin
version: @VERSION@
depend:
  - LuckPerms
commands:
  azipluginmessaging:
    permission: azipluginmessaging.use_command
